theme: jekyll-theme-minimal
minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
logo: "/assets/images/uchida.png"
title: "UchidaYuma Profile Site"
description: "Route Plus Co., Ltd. It is a site that introduces self-introduction and career of CEO Yuma Uchida."
author: Uchida Yuma
show_downloads: true
